<?php
/**
 * DATABASE CONFIGURATION
 *
 * For aaPanel / Live Server:
 * 1. Create a database in aaPanel.
 * 2. Use the "Username" and "Password" generated by aaPanel below.
 * 3. Most VPS servers use 'localhost' for DB_HOST.
 */

define('DB_HOST', 'localhost'); // Usually 'localhost' on aaPanel
define('DB_USER', 'root');      // REPLACE WITH YOUR AAPANEL DB USERNAME
define('DB_PASS', '');          // REPLACE WITH YOUR AAPANEL DB PASSWORD
define('DB_NAME', 'kiu_complaints'); // REPLACE WITH YOUR AAPANEL DB NAME

define('SITE_NAME', 'KIU Online Complaint System');
define('UPLOADS_DIR', 'uploads/attachments/');
define('ADMIN_SETUP_TOKEN', ''); // Set a long random value before using setup_admin.php or maintenance tools, then clear it afterwards.
?>
